name: Nexus Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8 

    - name: Login to GitHub Packages
        uses: actions/checkout@v3
        with:
          repository: sasidharsunny/Telus-app
          ref: 'main'
          token: ${{ secrets.G_TOKEN }}