name: Argo Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8 

    - name: Login to GitHub Packages
      uses: actions/checkout@v3
      with:
          repository: sasidharsunny/Telus-app
          ref: 'main'
          token: ${{ secrets.G_TOKEN }}

    - name: Update Replicas
      run: |
        # Modify the deployment.yaml file to set the desired number of replicas
        sed -i 's/replicas: [0-9]*/replicas: 5/' Deployment/deployment.yaml

        # Commit the changes
        git config --global user.email "sasidharsunny94@gmail.com"
        git config --global user.name "sasidharsunny"
        git add .
        git commit -m "Update replicas to 4"
        git push origin main  # Update the branch name as needed
