name: Argo Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8 

    - name: Login to GitHub Packages
      uses: actions/checkout@v3
      with:
          repository: sasidharsunny/Telus-app
          ref: 'main'
          token: ${{ secrets.G_TOKEN }}

  update-manifest-stage:
  runs-on: ubuntu-latest
  needs: ['build-and-push-docker-image']
    steps:
      - uses: actions/checkout@v3
        with:
          repository: imrishav/gitops-infra
          ref: 'master'
          token: ${{ secrets.G_TOKEN }}
      - name: setup git config
        run: |
          git config --global user.email "sasidharsunny94@gmail.com"
          git config --global user.name "sasidharsunny"
          echo ${{ github.sha }}
          sed -i "s#${{ github.actor }}.*#${{ github.actor }}/gitops01:${{ github.sha }}#g" deployment.yaml
          git add -A
          git commit -am "Update image for - ${{ github.sha }}"
      - run: echo ${{ github }}
      - run: git push origin main