name: Publish to JFrog Artifactory

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v1
      with:
        jfrog-cli-version: 'latest'
        artifactory-url: 'http://18.204.209.62:8081/'
      env:
        JFROG_CLI_HOME: /usr/local/bin

    - name: Build and Publish
      run: |
        # Build your application or package
        # Configure JFrog CLI with your Artifactory details using username and password
        jfrog config add MyArtifactory --artifactory-url=http://18.204.209.62:8081/artifactory/ --user=YOUR_USERNAME --password=YOUR_PASSWORD
        # Publish the artifact to JFrog Artifactory
        ./jfrog rt u --url=http://18.204.209.62:8081/artifactory --user=admin --password=admin@1234 test/file.jar test
      env:
       JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
       YOUR_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
       YOUR_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

